<a href="https://colab.research.google.com/github/louise-queiroz/treinamento-h2ia/blob/main/Buscas_com_informa%C3%A7%C3%A3o.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# O Problema
Sliding Puzzle - Bloco Deslizante

In [ ]:
# !wget -qq https://miro.medium.com/max/700/1*W7jg4GmEjGBypd9WPktasQ.gif
from IPython.display import Image
Image(url='https://miro.medium.com/max/700/1*W7jg4GmEjGBypd9WPktasQ.gif',width=200)

# Resolver o quebra-cabeças usando Buscas

## A*

In [43]:
import numpy as np
import time
from queue import PriorityQueue

class Node:
  def __init__(self, state, parent=None, action=None, g=0, h=0):
    self.state = np.array(state)
    self.children = []
    self.parent = parent
    self.action = action
    self.h = Node.heuristic(self.state)
    if self.parent is not None:
      self.g = parent.g + 1
    else:
      self.g = 0
    self.f = self.g + self.h

  def __eq__(self, other):
    return np.array_equal(self.state, other.state)

  def __lt__(self, other):
    return (self.f > other.f)

  def heuristic(board):
    goal = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 0]])
    h = 0
    for i in range(3):
        for j in range(3):
            if board[i][j] != goal[i][j] and board[i][j] != 0:
                h += 1
    return h

  def expand_node(self):
    zero_positions = np.argwhere(self.state == 0)

    if zero_positions.size > 0:
      zero_i, zero_j = zero_positions[0]

      if zero_i > 0:
        new_state = np.copy(self.state)
        new_state[zero_i, zero_j], new_state[zero_i - 1, zero_j] = new_state[zero_i - 1, zero_j], new_state[zero_i, zero_j]
        new_node = Node(new_state.tolist(), parent=self, action="Up", g=self.g + 1, h=self.h)
        self.children.append(new_node)
      if zero_i < 2:
        new_state = np.copy(self.state)
        new_state[zero_i, zero_j], new_state[zero_i + 1, zero_j] = new_state[zero_i + 1, zero_j], new_state[zero_i, zero_j]
        new_node = Node(new_state.tolist(), parent=self, action="Down", g=self.g + 1, h=self.h)
        self.children.append(new_node)

      if zero_j > 0:
        new_state = np.copy(self.state)
        new_state[zero_i, zero_j], new_state[zero_i, zero_j - 1] = new_state[zero_i, zero_j - 1], new_state[zero_i, zero_j]
        new_node = Node(new_state.tolist(), parent=self, action="Left", g=self.g + 1, h=self.h)
        self.children.append(new_node)

      if zero_j < 2:
        new_state = np.copy(self.state)
        new_state[zero_i, zero_j], new_state[zero_i, zero_j + 1] = new_state[zero_i, zero_j + 1], new_state[zero_i, zero_j]
        new_node = Node(new_state.tolist(), parent=self, action="Right", g=self.g + 1, h=self.h)
        self.children.append(new_node)


def aPathFinder(board):
  start = time.time()
  goal_state = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 0]])
  goal = Node(goal_state)
  visited = set()
  open_list = PriorityQueue()
  open_list.put((board.f,board))
  count = 0

  while open_list:
    count += 1
    current_node = open_list.get()[1]

    if np.array_equal(current_node.state, goal.state):
      path = []
      while current_node:
        path.append(current_node.state)
        current_node = current_node.parent
      end = time.time()
      execution_time = end - start
      return path[::-1], count, execution_time

    visited.add(tuple(map(tuple, current_node.state)))

    current_node.expand_node()  # Expand the current node to generate children

    for child in current_node.children:
      if tuple(map(tuple, child.state)) not in visited:
        open_list.put((child.f, child))

  return None, None, None


board_numbers = np.array([[0, 8, 7], [6, 5, 4], [3, 2, 1]])
board = Node(board_numbers)

result, count, time = aPathFinder(board)
if result:
    for matrix in result:
        print(np.array_str(matrix, max_line_width=np.inf))
    print(f"Tempo de execução: {time}")
    print(f"Iterações: {count}")
else:
    print("Não foi encontrada uma solução.")




[[0 8 7]
 [6 5 4]
 [3 2 1]]
[[8 0 7]
 [6 5 4]
 [3 2 1]]
[[8 7 0]
 [6 5 4]
 [3 2 1]]
[[8 7 4]
 [6 5 0]
 [3 2 1]]
[[8 7 4]
 [6 5 1]
 [3 2 0]]
[[8 7 4]
 [6 5 1]
 [3 0 2]]
[[8 7 4]
 [6 5 1]
 [0 3 2]]
[[8 7 4]
 [0 5 1]
 [6 3 2]]
[[0 7 4]
 [8 5 1]
 [6 3 2]]
[[7 0 4]
 [8 5 1]
 [6 3 2]]
[[7 4 0]
 [8 5 1]
 [6 3 2]]
[[7 4 1]
 [8 5 0]
 [6 3 2]]
[[7 4 1]
 [8 5 2]
 [6 3 0]]
[[7 4 1]
 [8 5 2]
 [6 0 3]]
[[7 4 1]
 [8 5 2]
 [0 6 3]]
[[7 4 1]
 [0 5 2]
 [8 6 3]]
[[0 4 1]
 [7 5 2]
 [8 6 3]]
[[4 0 1]
 [7 5 2]
 [8 6 3]]
[[4 1 0]
 [7 5 2]
 [8 6 3]]
[[4 1 2]
 [7 5 0]
 [8 6 3]]
[[4 1 2]
 [7 5 3]
 [8 6 0]]
[[4 1 2]
 [7 5 3]
 [8 0 6]]
[[4 1 2]
 [7 5 3]
 [0 8 6]]
[[4 1 2]
 [0 5 3]
 [7 8 6]]
[[0 1 2]
 [4 5 3]
 [7 8 6]]
[[1 0 2]
 [4 5 3]
 [7 8 6]]
[[1 2 0]
 [4 5 3]
 [7 8 6]]
[[1 2 3]
 [4 5 0]
 [7 8 6]]
[[1 2 3]
 [4 5 6]
 [7 8 0]]
Tempo de execução: 17.18380856513977
Iterações: 66676


#Versão otimizada

In [42]:
import numpy as np
import time
from queue import PriorityQueue

class Node:
    goal_state = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 0]])

    def __init__(self, state, parent=None, action=None, g=0, h=0):
        self.state = state
        self.parent = parent
        self.action = action
        self.g = g
        self.h = h
        self.f = self.g + self.h
        self.children = []  # Corrigir: Adicionando a lista de filhos aqui

    def __eq__(self, other):
        return np.array_equal(self.state, other.state)

    def __lt__(self, other):
        return self.f > other.f

    @staticmethod
    def heuristic(board):
        # Heurística: Distância de Manhattan
        distance = 0
        for i in range(3):
            for j in range(3):
                if board[i][j] != 0:
                    value = board[i][j] - 1
                    target_row = value // 3
                    target_col = value % 3
                    distance += abs(i - target_row) + abs(j - target_col)
        return distance

    def expand_node(self):
        zero_positions = np.argwhere(self.state == 0)
        zero_i, zero_j = zero_positions[0]

        for new_i, new_j in [(zero_i - 1, zero_j), (zero_i + 1, zero_j), (zero_i, zero_j - 1), (zero_i, zero_j + 1)]:
            if 0 <= new_i < 3 and 0 <= new_j < 3:
                new_state = np.copy(self.state)
                new_state[zero_i, zero_j], new_state[new_i, new_j] = new_state[new_i, new_j], new_state[zero_i, zero_j]
                new_node = Node(new_state, parent=self, action=f"({new_i},{new_j})", g=self.g + 1, h=Node.heuristic(new_state))
                self.children.append(new_node)

def aPathFinder(board):
    start = time.time()
    goal = Node.goal_state
    visited = set()
    open_list = PriorityQueue()
    open_list.put((board.f, board))
    count = 0

    while open_list:
        count += 1
        current_node = open_list.get()[1]

        if np.array_equal(current_node.state, goal):
            path = []
            while current_node:
                path.append(current_node.state)
                current_node = current_node.parent
            end = time.time()
            execution_time = end - start
            return path[::-1], count, execution_time

        state_string = ''.join(map(str, current_node.state.flatten()))
        visited.add(state_string)

        current_node.expand_node()

        for child in current_node.children:
            child_state_string = ''.join(map(str, child.state.flatten()))
            if child_state_string not in visited:
                open_list.put((child.f, child))
                visited.add(child_state_string)

    return None, None, None

board_numbers = np.array([[0, 8, 7], [6, 5, 4], [3, 2, 1]])
board = Node(board_numbers)

result, count, time_taken = aPathFinder(board)
if result:
    for matrix in result:
        print(np.array_str(matrix, max_line_width=np.inf))
    print(f"Tempo de execução: {time_taken}")
    print(f"Iterações: {count}")
else:
    print("Não foi encontrada uma solução.")


[[0 8 7]
 [6 5 4]
 [3 2 1]]
[[8 0 7]
 [6 5 4]
 [3 2 1]]
[[8 7 0]
 [6 5 4]
 [3 2 1]]
[[8 7 4]
 [6 5 0]
 [3 2 1]]
[[8 7 4]
 [6 5 1]
 [3 2 0]]
[[8 7 4]
 [6 5 1]
 [3 0 2]]
[[8 7 4]
 [6 5 1]
 [0 3 2]]
[[8 7 4]
 [0 5 1]
 [6 3 2]]
[[0 7 4]
 [8 5 1]
 [6 3 2]]
[[7 0 4]
 [8 5 1]
 [6 3 2]]
[[7 4 0]
 [8 5 1]
 [6 3 2]]
[[7 4 1]
 [8 5 0]
 [6 3 2]]
[[7 4 1]
 [8 5 2]
 [6 3 0]]
[[7 4 1]
 [8 5 2]
 [6 0 3]]
[[7 4 1]
 [8 5 2]
 [0 6 3]]
[[7 4 1]
 [0 5 2]
 [8 6 3]]
[[0 4 1]
 [7 5 2]
 [8 6 3]]
[[4 0 1]
 [7 5 2]
 [8 6 3]]
[[4 1 0]
 [7 5 2]
 [8 6 3]]
[[4 1 2]
 [7 5 0]
 [8 6 3]]
[[4 1 2]
 [7 5 3]
 [8 6 0]]
[[4 1 2]
 [7 5 3]
 [8 0 6]]
[[4 1 2]
 [7 5 3]
 [0 8 6]]
[[4 1 2]
 [0 5 3]
 [7 8 6]]
[[0 1 2]
 [4 5 3]
 [7 8 6]]
[[1 0 2]
 [4 5 3]
 [7 8 6]]
[[1 2 0]
 [4 5 3]
 [7 8 6]]
[[1 2 3]
 [4 5 0]
 [7 8 6]]
[[1 2 3]
 [4 5 6]
 [7 8 0]]
Tempo de execução: 0.06965017318725586
Iterações: 358


## Discorra sobre o desempenho dos métodos em questões de:


1.   Consumo de memória
2.   Processamento



In [ ]:
#O código está funcionando porém não está otimizado e sua execução é demorada.
#Rever código.